set -g prefix C-j
set-option -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",*256col*:Tc"
set-option -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"
set -s escape-time 0

# paste mode
set-window-option -g mode-keys vi
bind P paste-buffer
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi r send-keys -X rectangle-toggle
unbind -T copy-mode-vi y
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xsel -bi"

# 現在のパスで新しいwindowを開く
bind c new-window -c "#{pane_current_path}"
bind % split-window -hc "#{pane_current_path}"
bind '"' split-window -vc "#{pane_current_path}"


# Status Bar
# ref.
# - https://jamesatk.in/everforest-homepage/
# - https://github.com/talwat/dotfiles/blob/main/macOS/everforest/.tmux.conf
set -g status-bg "#343F44"
set -g status-fg white

set -g status-position top
set -g status-justify left
set -g status-style 'bg=colour18 fg=white'
set -g status-left ''
set -g status-right '#[fg=#3d484d,bg=#343f44]#[fg=white,bg=#3d484d] %d/%m #[fg=#9da9a0,bg=#3d484d]#[fg=#2d353b,bg=#9da9a0] %H:%M:%S '
set -g status-right-length 50
set -g status-left-length 20

setw -g window-status-current-style 'fg=#3d484d bg=#d3C6AA bold'
setw -g window-status-current-format ' #I#[fg=#475258]:#[fg=#3d484d]#W#[fg=#56635f]#F #[fg=#d3c6aa,bg=#343f44]'

setw -g window-status-style 'fg=white bg=#475258'
setw -g window-status-format ' #I#[fg=white]:#[fg=white]#W#[fg=white]#F '
