[tools]
"aqua:rossmacarthur/sheldon" = "latest"
bun = "latest"
fzf = "latest"
doggo = "latest"
gh = "latest"
ghcup = "latest"
ghq = "latest"
go = "1.25.6"
jq = "latest"
node = "lts"
ripgrep = "latest"
usage = "latest"
uv = "latest"

[env]
