[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
	let g:lightline = {'colorscheme': 'wombat'}
'''

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

